const mockData = {
  "result": "success",
  "data": {
    "document_type": "receipt",
    "amount": 2540,
    "amount_change": 0,
    "amount_shipping": 0,
    "amount_tip": 0,
    "vatamount": 232,
    "amountexvat": 2308,
    "currency": "EUR",
    "date": "2017-03-01T17:52:00",
    "purchasedate": "2017-03-01",
    "purchasetime": "17:52:00",
    "date_of_arrival": "",
    "date_of_departure": "",
    "vatitems": [
      {
        "amount": 101,
        "amount_excl_vat": 1683,
        "amount_incl_vat": 1784,
        "amount_incl_excl_vat_estimated": true,
        "percentage": 600,
        "code": ""
      },
      {
        "amount": 131,
        "amount_excl_vat": 624,
        "amount_incl_vat": 755,
        "amount_incl_excl_vat_estimated": true,
        "percentage": 2100,
        "code": ""
      }
    ],
    "vat_context": "",
    "lines": [
      {
        "description": "",
        "lineitems": [
          {
            "title": "Appelsap",
            "description": "",
            "amount": 250,
            "amount_each": 250,
            "amount_ex_vat": 250,
            "vat_amount": 0,
            "vat_percentage": 0,
            "quantity": 1,
            "unit_of_measurement": "",
            "sku": "",
            "vat_code": ""
          },
          {
            "title": "Bokbier",
            "description": "",
            "amount": 395,
            "amount_each": 395,
            "amount_ex_vat": 395,
            "vat_amount": 0,
            "vat_percentage": 0,
            "quantity": 1,
            "unit_of_measurement": "",
            "sku": "",
            "vat_code": ""
          },
          {
            "title": "Chardonnay",
            "description": "",
            "amount": 360,
            "amount_each": 360,
            "amount_ex_vat": 360,
            "vat_amount": 0,
            "vat_percentage": 0,
            "quantity": 1,
            "unit_of_measurement": "",
            "sku": "",
            "vat_code": ""
          },
          {
            "title": "Kinder pk",
            "description": "",
            "amount": 600,
            "amount_each": 600,
            "amount_ex_vat": 600,
            "vat_amount": 0,
            "vat_percentage": 0,
            "quantity": 1,
            "unit_of_measurement": "",
            "sku": "",
            "vat_code": ""
          },
          {
            "title": "Appel spek\nWinter Aktie:",
            "description": "",
            "amount": 0,
            "amount_each": 0,
            "amount_ex_vat": 0,
            "vat_amount": 0,
            "vat_percentage": 0,
            "quantity": 1,
            "unit_of_measurement": "",
            "sku": "",
            "vat_code": ""
          },
          {
            "title": "10 Van",
            "description": "",
            "amount": 935,
            "amount_each": 0,
            "amount_ex_vat": 935,
            "vat_amount": 0,
            "vat_percentage": 0,
            "quantity": 1,
            "unit_of_measurement": "",
            "sku": "",
            "vat_code": ""
          },
          {
            "title": "Gember kaas",
            "description": "",
            "amount": 935,
            "amount_each": 935,
            "amount_ex_vat": 935,
            "vat_amount": 0,
            "vat_percentage": 0,
            "quantity": 1,
            "unit_of_measurement": "",
            "sku": "",
            "vat_code": ""
          }
        ]
      }
    ],
    "paymentmethod": "cash",
    "payment_auth_code": "",
    "payment_card_number": "",
    "payment_card_account_number": "",
    "payment_card_bank": "",
    "payment_card_issuer": "",
    "payment_due_date": "",
    "terminal_number": "",
    "document_subject": "",
    "package_number": "",
    "invoice_number": "",
    "invoice_type": "",
    "receipt_number": "",
    "shop_number": "",
    "transaction_number": "",
    "transaction_reference": "",
    "order_number": "",
    "table_number": "",
    "table_group": "",
    "server": "",
    "merchant_name": "De Bijenmarkt",
    "merchant_id": "",
    "merchant_coc_number": "",
    "merchant_vat_number": "",
    "merchant_bank_account_number": "",
    "merchant_bank_account_number_bic": "",
    "merchant_chain_liability_bank_account_number": "",
    "merchant_chain_liability_amount": 0,
    "merchant_bank_domestic_account_number": "",
    "merchant_bank_domestic_bank_code": "",
    "merchant_website": "",
    "merchant_email": "",
    "merchant_address": "Nieuweweg-Noord 267A",
    "merchant_street_name": "Nieuweweg-Noord",
    "merchant_house_number": "267A",
    "merchant_zipcode": "3905 LM",
    "merchant_city": "Veenendaal",
    "merchant_municipality": "",
    "merchant_province": "",
    "merchant_country": "",
    "merchant_country_code": "NL",
    "merchant_phone": "0318506469",
    "merchant_main_activity_code": "",
    "customer_name": "",
    "customer_number": "",
    "customer_reference": "",
    "customer_address": "",
    "customer_street_name": "",
    "customer_house_number": "",
    "customer_zipcode": "",
    "customer_city": "",
    "customer_municipality": "",
    "customer_province": "",
    "customer_country": "",
    "customer_phone": "",
    "customer_vat_number": "",
    "customer_coc_number": "",
    "customer_bank_account_number": "",
    "customer_bank_account_number_bic": "",
    "customer_website": "",
    "customer_email": "",
    "payment_slip_code": "",
    "payment_slip_reference_number": "",
    "payment_slip_customer_number": "",
    "document_language": "NL",
    "personal_income_tax_amount": 0,
    "personal_income_tax_rate": 0,
    "matched_keywords": null,
    "matched_lineitems": null,
    "matched_purchase_order_id": "",
    "barcodes": null,
    "hash": "1b4ab6e9321226f93530fda1a15e2e3ddec051f4",
    "hash_duplicate": true,
    "raw_text": "           Pannenkoekenhuis\n            De Bijenmarkt\n             Nieuweweg-Noord 267A\n             3905 LM Veenendaal\n                0318-506469\n                   1. Kopie\nTafel #36\n1 x Appelsap                           2,50\n1 x Bokbier                            3,95\n1 x Chardonnay                         3,60\n1 x Kinder pk                          6,00\n1 x Appel spek                         0,00\nWinter Aktie:\n100,00% Van 9,35 -\u003e 0,00\n1 x Gember kaas                        9,35\nTotaal                            25,40\nBtw laag                               1,01\nBtw hoog                               1,31\nContant                           25,40\n17:52 01/03/17 103 Mariette              25\nKassa 2 MP\n    Bedankt voor uw bezoek en tot ziens.\n         www.pannenkoekenhuizen.com\n               De Bijennarkt\n      U bent geholpen door Mariette"
  },
  "request_id": "SkCooYCfyp4K0QLpTTvR8QaaXYzclDUw"
}

export default mockData;
